[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "VMware"
  identifier = "Links2"
  weight = -109
  [[main]]
  parent = "Links2"
name = "Configure VMware Horizon View  Direct-Connection Agent for Linux"
  url = "post/2021/12/30/horizon_view_direct_connection_to_linux_vm/"
 

[[main]]
  name = "Tags"
  identifier = "Links1"
  weight = -107
  [[main]]
  parent = "Links1"
  name = "Packer"
  url = "tags/packer"
  [[main]]
  parent = "Links1"
  name = "Terraform"
  url = "tags/terraform"

[[main]]
  name = "Certifications"
  url = "https://www.credly.com/users/daniel-hanaj/badges?sort=-state_updated_at&page=1"
  weight = -106


[[main]]
  name = "About"
  url = "about/"
  weight = -105

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/#"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/danielhanaj"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/danielhanaj"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"